### ISSUE TITLE
Source code of last update (2.0.2.5)

### ISSUE THREAD

**Issue by dark22** [Megghy/TSManager#3]
Hi, it is noticeable that you are moving the code for the future update of TShock based on OTAPI3 and .Net5, however the last updated source code is from version 2.0.2.4 and not from the latest 2.0.2.5. Unfortunately some errors occur when trying to load the server with the outdated version. Could you submit the changes for the new version? I think I owe you a coffee for your great open source projects!  Thanks.

**Comment by Megghy** [comment]
Unfortunately, since the refactoring code was written directly from the old repository, the previous code has been lost.
I think you'd be better off waiting until the new version is finished, which will probably support localization and multi-server management, and of course I'd try to use better code. 
If you really want to continue using this version and have some experience with the code, you can clone the repository and simply change the references and compile

**Comment by dark22** [comment]
Thank you very much for your attention. I'll check later if I can fix the current version so that it works properly with TShock, as apparently it might take a while to update. I am very happy to hear that there is development with support for multiple servers and languages. I would like to help with this, but my knowledge of C# is quite limited. All good for you!
